services:
  tika-metadata-tool:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - /Users/user/data:/data
      - /Users/user/logs:/logs
      - /Users/user/output:/output
      - /Users/user/excel:/excel